### ISSUE TITLE
Shortcut_CopySelectedTextAsBlockRefAlias not working on Windows

### ISSUE THREAD

**Issue by nhan000** [vyleung/logseq-quick-add-plugin#2]
Windows Desktop 0.7.0

Have tried changed the `Shortcut_CopySelectedTextAsBlockRefAlias` to multiple other keybinds but still doesn't work. All other features work well for me.

Maybe it's just my laptop that has issue? Submit this to see if any other Windows users have the same problem.

**Comment by vyleung** [comment]
can you open dev tools (`ctrl+shift+i`) and see if there are any errors when you try to use the keybinding?

**Comment by nhan000** [comment]
I think it's this? If not let me know what info I need to provide to you.

![image](https://user-images.githubusercontent.com/85216095/170668311-4c88eb64-6afa-4235-9478-986ace603e39.png)

**Comment by vyleung** [comment]
ah i see - it's a cross-origin error. i've submitted a [pull request](https://github.com/logseq/marketplace/pull/188) in the marketplace to address this issue

until the PR has been merged, please download [v.1.1.1](https://github.com/vyleung/logseq-quick-add-plugin/releases/tag/v.1.1.1) from github and load the plugin manually - let me know if you still run into the issue using this method

**Comment by nhan000** [comment]
The manually loaded plugin works as expected. Thanks so much!
