### ISSUE TITLE
Don't lose 'focus'

### ISSUE THREAD

**Issue by Pantybra** [vyleung/logseq-quick-add-plugin#3]
When I have duplicated one or more blocks, I have lost focus, i.e., *it exits the Journal and I would like to continue editing on the recently duplicated blocks.* I waste time re-entering to edit the desired block.
(Or something I making bad)

**Comment by vyleung** [comment]
hi, sorry for the late response! i've added an option for this in v.1.2.1. please update the plugin and enable this feature in the settings
